### ISSUE TITLE
error npm install

### ISSUE THREAD

**Issue by speedtechj** [tuandm/laravue-core#6]
ENOENT: no such file or directory, open '/Users/newowner/laravue/node_modules/.staging/@types/jquery-fc08fbbe/JQueryStatic.d.ts'
npm ERR! Error while executing:

**Comment by dfrey382** [comment]
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.npm ERR! Error while executing:
npm ERR! C:\laragon\bin\git\bin\git.EXE ls-remote -h -t git://github.com/adobe-webplatform/eve.git
npm ERR! 
npm ERR! fatal: unable to look up github.com (port 9418) (Either the application has not called WSAStartup, or WSAStartup failed. )
npm ERR! 
npm ERR! exited with error code: 128

**Comment by feller23** [comment]
After Adding Laravue-core to my already existing laravel Application. Serving any page in my app gives me a blank white screen even after turning on debug on app.php.

**Comment by tuandm** [comment]
@dfrey382 From the error log, your machine doesn't support git:// protocol. You can look around to find the solution. For instance: https://stackoverflow.com/questions/53477460/git-pull-fails-with-either-the-application-has-not-called-wsastartup-or-wsasta. I'm closing this issue because it's not related to the library.
